FROM python:3.6

# Creating Application Source Code Directory
RUN mkdir -p /python-app/src

WORKDIR /python-app/src

# Copying src code to Container
COPY . /python-app/src/app

# Application Environment variables
ENV APP_ENV development

# Exposing Ports
EXPOSE 5000

# Setting Persistent data
VOLUME ["/app-data"]

# Running Python Application
CMD ["python", "app.py"]
