apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
        version: 1.0.1
    spec:
      containers:
        - image: python-app:1.0.1 
          name: python-app
          ports:
            - containerPort: 5000
              name: python-app
---
apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  namespace: application
  labels:
    app: python-app
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: python-app
    version: 1.0.1
  type: NodePort

